package Microservice.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_InputPort;
  private ConceptPresentation props_Interface;
  private ConceptPresentation props_OutputPort;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_RequestResponseMessage;
  private ConceptPresentation props_RequestType;
  private ConceptPresentation props_ResponseType;
  private ConceptPresentation props_ThrowMessage;
  private ConceptPresentation props_microservice;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.InputPort:
        if (props_InputPort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InputPort = cpb.create();
        }
        return props_InputPort;
      case LanguageConceptSwitch.Interface:
        if (props_Interface == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Interface = cpb.create();
        }
        return props_Interface;
      case LanguageConceptSwitch.OutputPort:
        if (props_OutputPort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_OutputPort = cpb.create();
        }
        return props_OutputPort;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.RequestResponseMessage:
        if (props_RequestResponseMessage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RequestResponseMessage = cpb.create();
        }
        return props_RequestResponseMessage;
      case LanguageConceptSwitch.RequestType:
        if (props_RequestType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RequestType = cpb.create();
        }
        return props_RequestType;
      case LanguageConceptSwitch.ResponseType:
        if (props_ResponseType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ResponseType = cpb.create();
        }
        return props_ResponseType;
      case LanguageConceptSwitch.ThrowMessage:
        if (props_ThrowMessage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ThrowMessage = cpb.create();
        }
        return props_ThrowMessage;
      case LanguageConceptSwitch.microservice:
        if (props_microservice == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_microservice = cpb.create();
        }
        return props_microservice;
    }
    return null;
  }
}
