package Microservice1.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Execution = 0;
  public static final int InputPort = 1;
  public static final int Interface = 2;
  public static final int Node = 3;
  public static final int Operation = 4;
  public static final int OutputPort = 5;
  public static final int Port = 6;
  public static final int RequestMessageType = 7;
  public static final int RequestResponse = 8;
  public static final int ResponseMessageType = 9;
  public static final int microservice = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5c89a8404b0c458cL, 0x8389f58f5a50822bL);
    builder.put(0x17f752bd37f0c70cL, Execution);
    builder.put(0x7921bd26331619ebL, InputPort);
    builder.put(0x7921bd2633149458L, Interface);
    builder.put(0x7921bd263315e3aaL, Node);
    builder.put(0x7921bd2633149e27L, Operation);
    builder.put(0x7921bd263316276cL, OutputPort);
    builder.put(0x7921bd26331612b8L, Port);
    builder.put(0x7921bd26331575adL, RequestMessageType);
    builder.put(0x7921bd263314aabbL, RequestResponse);
    builder.put(0x7921bd2633158633L, ResponseMessageType);
    builder.put(0x17f752bd37f0a959L, microservice);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
